[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
spore = "9HvZ7ckadQt38R1KxYPhP759yCCx4MRF8NBquV4HUUXZ"

[programs.localnet]
spore = "GVKoapVqZCBNWkuHopCZSFDqBGimxHWuHsFeoEcVd4Me"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
